### ISSUE TITLE
[Client] Handle unavailable server.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [katevi/Chat#13]
In case server for the message transfer (back-end) is unavailable, a client should be notified within GUI.
As for now, we can determine what's wrong only in case we'd open the console, which is not the most sufficient way to determine errors in front end.
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/22101169/79004313-2ae44780-7b5d-11ea-8958-96f739872c75.png">

**Comment by katevi** [comment]
Handling this case was implemented and merged into master.
