### ISSUE TITLE
Add ability to set avatar.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [katevi/Chat#20]
User should be able to have an avatar. 
The avatar saving alhorythm:
1. User clicks "Set profile picture" button from front-end;
2. Loads the picturel
3. Clicks "save changes";
4. The picture is going to the persistent storage.

If user hasn't set an avatar, a default one (for example: the `?` picture) is assigned.

Note that it'd require changing of user entity. Information about the user should also contain its avatar.

**Comment by katevi** [comment]
I investigated a bit and found [this] (https://dzone.com/articles/upload-and-retrieve-filesimages-using-spring-boot) and [this](https://medium.com/@udith.indrakantha/upload-images-and-save-them-in-a-database-angular-8-spring-boot-mysql-b5144768202b) articles.
Do I correctly understand that we need to:
1) send file (picture) from client to server
2) save picture in database
3) when user logins, find by user's name in JPA repository his avatar and send it to client? :)

**Comment by AndreyKoltsov1997** [comment]
> I investigated a bit and found [this] (https://dzone.com/articles/upload-and-retrieve-filesimages-using-spring-boot) and [this](https://medium.com/@udith.indrakantha/upload-images-and-save-them-in-a-database-angular-8-spring-boot-mysql-b5144768202b) articles.
> Do I correctly understand that we need to:
> 
> 1. send file (picture) from client to server
> 2. save picture in database
> 3. when user logins, find by user's name in JPA repository his avatar and send it to client? :)
>    (or we have not to do step 3 in this PR?)

At high level - yep.
I'd start ASAP since there could be issues with picture encoding.

**Comment by katevi** [comment]
Do we actually need to store default avatars in db? Maybe it would be better to store null value in field avatar in db, check if avatar is default in the client-part and upload it from  the client? We can avoid extra sending picture from server to client and duplicate files (since we still need to store default avatar in the client part if user will register without picture).

**Comment by AndreyKoltsov1997** [comment]
> Do we actually need to store default avatars in db? Maybe it would be better to store null value in field avatar in db, check if avatar is default in the client-part and upload it from the client? We can avoid extra sending picture from server to client and duplicate files (since we still need to store default avatar in the client part if user will register without picture).

In our case, it'd be more convenient to store it as a static file within the front-end, yes.
