### ISSUE TITLE
Direct messages.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [katevi/Chat#21]
**Now**
We have a single chat. Every logged user could write into it.

**Then**
Users should have ability to send and/or receive direct messages.

**Comment by AndreyKoltsov1997** [comment]
**Please, investigate the:**
1. How to validate login attempt; 
2. Token generation logic in server;
3. OAuth (front-end);

**Comment by katevi** [comment]
I have some questions :)

1) I have read [this](https://www.baeldung.com/spring-websockets-send-message-to-user) and [this](https://www.baeldung.com/spring-websockets-sendtouser) articles and figured out that if we want to send message to specific user, we need to send it in /user/{username} with @SendToUser annotation.
2) After that I have stucked with problem that I do not know, how recipient will receive message and send answer, if he does not know, which user sent him messages:
- assume that there is a placeholder wher user can put recepient nickname, and after subscribe to the "user/{recepientUsername}" endpoint.
- if recepient will have such endpoint too, he will capture all messages from users:/
3) Also I have investigated [this](https://stackoverflow.com/questions/45308500/private-messages-spring-websocket) answer and have found [this](https://github.com/MatthewVita/spring-boot-private-chat/blob/master/src/main/java/org/privatechat/chat/controllers/ChatChannelController.java) and [this](https://github.com/salmar/spring-websocket-chat) repositories. In first repo creator has entity of chat channel, but I still do not see how recepient "connects" to the private chat with someone, when receives message from this someone:(
4) For what we need token generation and OAuth? I have read [this](https://www.varonis.com/blog/what-is-oauth/) article, and I do not see how it might be useful for direct messages:(
Main points:
* I do not understand, how to recipient connect to direct chat
* I do not understand, for what we need OAuth in this PR

**Comment by AndreyKoltsov1997** [comment]
I thought OAuth might be useful to access user’s direct messages. We don’t want non-authenticated users to view persona messages. 
Please, do not a separate ‘../recepentiName’ endpoint. Alternatively, you could embed information about recipient in JSON.

**Comment by katevi** [comment]
Anyway, I did not really understand how this should happen: the user received a token and can view a list of dialogs? I just did not plan to store them yet, I wanted to do something like two buttons "go to general chat" (where all users see each other's messages) and "write X" (direct).
And how can you view other people's messages if you do not give a token?

**Comment by katevi** [comment]
Or is the option with two buttons (and transition to two types of dialogs) not acceptable?
And yet I still do not understand how the user to whom someone sent the message to understand who it came from? Or should he catch those who want to chat with him in some kind of endpoint (for example, someone sent a request for communication and can we start a dialogue with the first such user?)
endpoint is one for all users, e.g. user / wanters-to-talk (edited)

**Comment by katevi** [comment]
Maybe we can implement such variant:
- A wants to send message to B
- Server generates channel UUID and returns it to A as response
- A subscribes to users/direct/dialogue-UUID
- B waits for conversations
- B receives A nickname in endpoint users/wanting-to-talk
- B presses button "talk with A" (or even without button, B may wait until someone talk with him)
- B receives direct chat UUID and subscribes to users/direct/dialogue-UUID
- dialogue = broadcast in users/direct/dialogue-UUID

**Comment by AndreyKoltsov1997** [comment]
Please, close all of the issues that are no longer relevant - either done or invalid.
