### ISSUE TITLE
[4] Investigate User Metadata Persistence.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [katevi/Chat#8]
Before start of implementations functionality for users support, we first have to do the investigation in order to construct the path of tasks or it.
I'll ask you the question that may help.

Let's assume a user account would contain nickname, full name and a password.

**Back-end**
1. How to persist user metadata? 
2. Would you want to persist chat history? If yes, how?

**Front-end**
3. Think about the sign in / sign up process. Read about best practices for it.

**Comment by katevi** [comment]
I part : **Registration process**
0. When user enters application, front server sends registration page.
1. User fills registration form in this page (nickname, full name, password).
2. Gathered data from the registration form packs in json format and is sends to the back server in special endpoint (post request in user/registration).
3. Back server takes json object from this endpoint.
4. Validation process: check that all fields is non-empty and new user's nickname is unique.
5. Add new user in UserRepository (which extends CRUD repository).
6. Hash received password with Bcrypt (read about it below).
7. Send message to the front server about successfully registered user.
8. Front server sends chat page to the new user.

**Comment by katevi** [comment]
**II part : why is Bcrypt?**

**Comment by AndreyKoltsov1997** [comment]
> **I part : registration process**
> 
> 1. When user enters application, front server sends registration page.
> 2. User fills registration form in this page (nickname, full name, password).
> 3. Gathered data from the registration form packs in json format and is sends to the back server in special endpoint (post request in user/registration).
> 4. Back server takes json object from this endpoint.
> 5. Validation process: check that all fields is non-empty and new user's nickname is unique.
> 6. Add new user in UserRepository (which extends CRUD repository).
> 7. Hash received password with Bcrypt (read about it below).
> 8. Send message to the front server about successfully registered user.
> 9. Front server sends chat page to the new user.
> 
> I have read registration scenario in this series of articles : https://www.baeldung.com/spring-security-registration.
Let's separate validation into 2 parts:
1. validate the correctness of the entered data (non-empty fields, requirements match, etc) in front-end side. In other words: **everything that don't need any interaction with the server (back end) in order to be validated should be done in browser.**
2. validate the logical correctness of parameters: uniqueness of the username, etc. 
For example: in order to validate username uniqueness, we'd have to query the database and check if the name exists there.

Note that you'd have to deal with JavaScript promises in order to get the server response. A possible way to handle responses over HTTP is to use `axios`.  Read [How to Use Axios to Make HTTP Requests – GET, POST and Parallel Requests](https://dev.to/ryancal/how-to-use-axios-to-make-http-requests-get-post-and-parallel-requests-3kn9)

**Comment by AndreyKoltsov1997** [comment]
A couple questions regarding data persistence:
1. Which database would you use and why?
2. Have you thought about the schema of it? If yes, could you provide a mock-up for it?

**Comment by katevi** [comment]
**III part: database choice**
I found some articles, which purpose is help to choose db for project :
[https://www.futurehosting.com/blog/choosing-a-database-for-your-web-application/]
[https://ukieweb.com/blog/which-database-is-best-for-your-web-development-project]
[https://blog.panoply.io/postgresql-vs-mongodb]
As I have read in this articles, there are some things, worth noting:
1. NoSQL databases (like MongoDB) *"is not built for transactional data (accounting systems, etc.)"*, so, but reliable transaction for adding user's credentials (and password) seems important for us.
2. on the other hand, Chat not requires complicated operations with data (like join, for example), so SQL database will provide extra opportunities, which are not necessary.
3. there is PostgreSQL, which provides us a lot of NoSQL features, but they are not native and, consequently, might be less eficient, rather than NoSQL db-s
4. MongoDB , as NoSQL db, is better scalable (I think is useful, if we want to store chat data)
5. man from Quora says, that MongoDB extremely fits for messages with emoticons and photos, since we can simply save it in JSON string [https://www.quora.com/Is-mongoDB-a-suitable-solution-for-a-web-based-chat-application] 
6. as I saw, there a lot of articles about PostgreSQL vs MongoDB (since PostgreSQL considered very popular and uses NoSQL features) [https://www.mongodb.com/compare/mongodb-postgresql], [https://blog.panoply.io/postgresql-vs-mongodb]

**Comment by katevi** [comment]
IV part: database mock-up

**Comment by AndreyKoltsov1997** [comment]
> **III part: database choice**
> I found some articles, which purpose is help to choose db for project :
> [1](https://www.futurehosting.com/blog/choosing-a-database-for-your-web-application/), [2](https://ukieweb.com/blog/which-database-is-best-for-your-web-development-project), [3](https://blog.panoply.io/postgresql-vs-mongodb)
> As I have read in this articles, there are some things, worth noting:
> 
> 1. NoSQL databases (like MongoDB) _"is not built for transactional data (accounting systems, etc.)"_, but reliable transaction for adding user's credentials (and password) seems important for us.
> 2. on the other hand, Chat not requires complicated operations with data (like join, for example), so SQL database will provide extra opportunities, which are not necessary.
> 3. there is PostgreSQL, which provides us a lot of NoSQL features (we may need them during work with JSON object), but they are not native and, consequently, might be less eficient, rather than in pure NoSQL db-s
> 4. MongoDB, as NoSQL db, is better scalable (I think is useful, if we want to store chat data)
> 5. man from Quora [says](https://www.quora.com/Is-mongoDB-a-suitable-solution-for-a-web-based-chat-application), that MongoDB extremely fits for messages with emoticons and photos, since we can simply save it in JSON string
> 6. as I saw, there a lot of articles ([1](https://www.mongodb.com/compare/mongodb-postgresql),[2](https://www.mongodb.com/compare/mongodb-postgresql)) about PostgreSQL vs MongoDB
> 
> **Updated**
> I reread [this](https://www.mongodb.com/compare/mongodb-postgresql) article and found, that MongoDB provides ACID garantees and _"Through snapshot isolation, transactions provide a consistent view of data, and enforce all-or-nothing execution to maintain data integrity."_, so it seems to be it suits for storing user credentials also.
> To conclude, I fully agree with your idea to use MongoDB.
> 
> P.S. I learned, how to create links in Markdown=)

Great research! Keep in mind that, even though MongoDB fits the our chat's pet-project, you'd have to add more selection cafeterias when you'd be developing a HA messaging application.
I'd suggest you to go through 
* [User Data Management with MongoDB](https://www.mongodb.com/presentations/user-data-management-mongodb) (the article seems to be pretty old, but the concept and the main ideas of it shouldn't change);
* [How can I store the chatting messages in my web application using MySQL?
](https://www.quora.com/How-can-I-store-the-chatting-messages-in-my-web-application-using-MySQL) - it has some ideas regarding the schema of the DB;

**Comment by AndreyKoltsov1997** [comment]
> **IV part: database mock-up**
> I've thought about doingh sth similar with [this](https://spring.io/guides/gs/accessing-mongodb-data-rest/), or [especially this](https://medium.com/javarevisited/building-a-rest-service-with-spring-boot-and-mongodb-3aa5cd2dce73) articles:
> 
> * there will be entity User with fields _nickname_, _fullname_, _password_ (in spring tutorial it is called domain object)
> * there will be UserRepository with CRUD (firstly, create and read, after maybe update too - if user wants to take new nickname, or change full name), it should have following methods:
>   
>   * findUserByNickname
> * there will be UserService, which has UserRepository and handle all requests to it (it will be wrapper on UserRepository
> * there will be RestController with PostMapping to saveOrUpdateUser

Great.
I think it'd be useful to also add the timestamp of the registration. Let's start the implementation and probably we'd come up with more ideas on the way.
